timestamp = 2023-02-03T21:48:05Z
github = { repo = "input-output-hk/ouroboros-network", rev = "358880057f1d6d86cc385e8475813ace3b9ebef6" }
subdir = 'ouroboros-consensus-mock-test/'
force-version = true
